### ISSUE TITLE
Missing Dependency in Requirements.txt

### ISSUE THREAD

**Issue by Mossy-x** [Arrayem/rs-name-checker#2]
`Traceback (most recent call last):`
`File "C:\Users\xxx\Downloads\Runescape-Name-Checker-main\main.py", line 8, in <module>`
`import functions.copy`
`File "C:\Users\xxx\Downloads\Runescape-Name-Checker-main\functions\copy.py", line 1, in <module>`
`    import pyperclip`
`ModuleNotFoundError: No module named 'pyperclip'`

After manually installing pyperclip the program worked as expected

**Comment by aellas** [comment]
Thanks for the heads up! 
Updated requirements.txt
